INSERT INTO role_table (role_id, role_name, created_at, updated_at, created_by) VALUES
(1, 'SUPER_ADMIN', CURRENT_TIMESTAMP, NULL, 'SUPER_ADMIN'),
(2, 'ADMIN', CURRENT_TIMESTAMP, NULL, 'SUPER_ADMIN'),
(3, 'ADMIN_SERVICE_PROVIDER', CURRENT_TIMESTAMP, NULL, 'SUPER_ADMIN'),
(4, 'SERVICE_PROVIDER', CURRENT_TIMESTAMP, NULL, 'SUPER_ADMIN'),
(5, 'CUSTOMER', CURRENT_TIMESTAMP, NULL, 'SUPER_ADMIN');
